language: go

go:
  - 1.1
  - 1.4
  - 1.5
  - 1.6

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

script:
  - go vet
  - go test -v
  - $HOME/gopath/bin/goveralls -service=travis-ci